### ISSUE TITLE
Screen scale is too small when running on M1 macbook pro

### ISSUE THREAD

**Issue by halpz** [GTAmodding/re3#1173]
the game fills only a portion of the screen on retina MBP m1 (arm64)

https://i.imgur.com/He9YhIc.png

**Version**
MacOS 64bit OpenGL OAL 22e8e0ef

**Comment by erorcun** [comment]
I thought this was solved. Was that happening in January-February?

**Comment by halpz** [comment]
yes i believe so!

**Comment by Grimones** [comment]
Try cmd+tab and then opening it back. That fixes for me VC

**Comment by halpz** [comment]
this doesnt fix it for me - both III and VC have zoomed-in screens, (only on retina macbook screen, it seems to behave on an external monitor)

it is probably related to the different screen pixel density scale in mac os when using a retina screen.
