### ISSUE TITLE
Possibility of building in ARM64?

### ISSUE THREAD

**Issue by Lang-Kasempo** [GTAmodding/re3#719]
I know this has a .nro version, and I was curious if this could be ALSO build to be used on L4T Ubuntu for Nintendo Switch, cause for what I can see, it only supports x86/AMD64 builds

**Comment by ShFil119** [comment]
As long as you have required libs it should work on generic arm.  Try `linux-arm-librw_gl3_glfw-oal` target and follow linux guide.

**Comment by Lang-Kasempo** [comment]
Ok, I will, thanks

**Comment by Lang-Kasempo** [comment]
Yeah, Switch doesn't have support for 32 bit libs. That is why I'm asking

**Comment by ShFil119** [comment]
Can you try again with `linux-arm64-librw_gl3_glfw-oal`?

**Comment by Lang-Kasempo** [comment]
Ok, I will

**Comment by Lang-Kasempo** [comment]
Fun Fact: You can't even do ./premake5Linux --with-librw gmake2 cause it gives binary error... yay

**Comment by erorcun** [comment]
yeah, you have to compile premake5 for ARM first. (we've tried that before and it worked)

**Comment by Lang-Kasempo** [comment]
Oh, how do I do that if I can know?

**Comment by Lang-Kasempo** [comment]
Oh, how do I do that if I can know?
Sorry for annoying both of you ^^"

**Comment by myfreeweb** [comment]
You can just get premake5 from your OS's package repository

**Comment by Lang-Kasempo** [comment]
![Captura de pantalla de 2020-09-27 18-35-57](https://user-images.githubusercontent.com/69186495/94379890-56012a00-00f0-11eb-8e35-e8f935068ccf.png)

**Comment by Lang-Kasempo** [comment]
Forget it, Ubuntu repo had glfw 3.2 instead of 3.3, so I have to build it myself and now it works :D

**Comment by myfreeweb** [comment]
Looks like you're using the *headers* from your build of glfw, but *linking* to the system glfw library.

**Comment by Lang-Kasempo** [comment]
Oh, that makes sense.

**Comment by parkerlreed** [comment]
Did the configuration get renamed?

```
[parker@alarm re3]$ cd build/
[parker@alarm build]$ make config=linux-arm64-librw_gl3_glfw-oal -j4
Makefile:44: *** "invalid configuration linux-arm64-librw_gl3_glfw-oal".  Stop.
```

**Comment by parkerlreed** [comment]
Works great with Arch Linux ARM on the Nintendo Switch.

**Comment by Lang-Kasempo** [comment]
![Captura de pantalla de 2020-09-28 07-13-14](https://user-images.githubusercontent.com/69186495/94436820-24bd4400-015a-11eb-82ee-c68862a1fce7.png)

**Comment by ShFil119** [comment]
Do you have installed also lib for devs? `libglfw3` and `libglfw3-dev`

**Comment by aap** [comment]
This is actually a problem with static vs. dynamic linking against glfw. you have to build the other thing.

**Comment by Lang-Kasempo** [comment]
Fixed, but now I got black screen

**Comment by ShFil119** [comment]
It can compile shaders at first run.

**Comment by Lang-Kasempo** [comment]
How much?

**Comment by aap** [comment]
What version of opengl do you have? If you don't have desktop gl but only gles you have to build librw differently. It's a bit of a hack right now because i still don't know where i want to go with the gl backend eventually, but for the moment you have to put `defines { "RW_GLES" }` into the premakefile. Do be aware though that the custom shaders in re3/reVC are NOT implemented for gles2 yet, sorry about that.

**Comment by Lang-Kasempo** [comment]
It uses gl, not gles

**Comment by aap** [comment]
ok. then i don't know.

**Comment by Lang-Kasempo** [comment]
![Captura de pantalla de 2020-09-28 09-05-40](https://user-images.githubusercontent.com/69186495/94449933-ddd74a80-0169-11eb-8781-8ee016ba2542.png)

**Comment by ShFil119** [comment]
Ofc you moved binary into your gta3 folder?

Can you try to run from terminal? `./re`

**Comment by Lang-Kasempo** [comment]
I actually run from terminal, and yeah, here is my folder:
![Captura de pantalla de 2020-09-28 09-13-37](https://user-images.githubusercontent.com/69186495/94450783-ec723180-016a-11eb-8ee8-57996c67da70.png)

**Comment by ShFil119** [comment]
What's an output?

**Comment by Lang-Kasempo** [comment]
How can I disable full screen? I get softlock in full screen

**Comment by ShFil119** [comment]
First, can you run game from terminal and alt + tab? Or ctrl + f2 and kill process?

**Comment by Lang-Kasempo** [comment]
![Captura de pantalla de 2020-09-28 09-57-05](https://user-images.githubusercontent.com/69186495/94456894-16c6ed80-0171-11eb-90e5-f43f0b3b5965.png)

**Comment by erorcun** [comment]
I have to ask that, do you have /models/fonts.txd?

**Comment by Lang-Kasempo** [comment]
Nope, I'm guessing that its in the re3 folder?

**Comment by erorcun** [comment]
it's part of game

**Comment by Lang-Kasempo** [comment]
Well shit, let me see what the hell happened then...

**Comment by Lang-Kasempo** [comment]
GOT IT TO WORK

**Comment by erorcun** [comment]
from graphics menu, should be named Screen Format

**Comment by Lang-Kasempo** [comment]
Thanks for all the help. Maybe in the future we are gonna include this in our megascript: 
https://github.com/cobalt2727/L4T-Megascript
Given you credit ofc. For now I will test how well it runs. Thanks again for everything. Have a good Monday

**Comment by erorcun** [comment]
thanks.
